### ISSUE TITLE
Working from web.postman but not from Hassio....

### ISSUE THREAD

**Issue by mupsje** [gajosu/whatsapp-ha-addon#8]
Hi, I have my system behind a cloudflare tunnel.
I have all setup and working...

Hassio running on: https://ha.mydomain.nl  - http://192.168.20.220:8123
The whatsapp addon: https://whatsapp.mydomain.nl   - http://192.186.20.220:3000

When I sent a POST from web.postman.co  I receive a message on whatsapp. So I know it is working
like: 
<img width="325" alt="image" src="https://user-images.githubusercontent.com/46684538/227932148-330f84f7-963a-4908-80eb-8ff279477155.png">

But when I try to sent from Hassio it does not work..
<img width="613" alt="image" src="https://user-images.githubusercontent.com/46684538/227932478-f80ac8f2-b980-4ea7-b388-9f1fc35a0891.png">

This is in my config.yaml
<img width="330" alt="image" src="https://user-images.githubusercontent.com/46684538/227933894-4396b562-cf7d-4290-86c7-4a445f33a58e.png">

please advise...
Thank you

**Comment by gajosu** [comment]
Hi, this seems to be more of a cloudflare issue, cloudflare tunnels have anti-bot filters and ddos attacks, probably cloudfalre is denying the request being made from HA, maybe because it thinks it's a bot, you need to create rules of filter to prevent this from happening, or else what I recommend is to use the ip and the port directly since the requests will always be made from your internal network, it is not necessary that you put the domain

**Comment by mupsje** [comment]
Thanks for the answer, I will indeed seek for that filter thing.
I also tried to do that with the IP-adres and port directly , also no succes.

I will update tomorrow. 
again thanks for the answer

**Comment by gajosu** [comment]
I recommend that you do it through an internal network, since this addon is not designed to be exposed to the Internet, it does not have any type of authentication

**Comment by gajosu** [comment]
Oh, I didn't know that, thank you very much, could you create a pr fixing this? I would greatly appreciate it

**Comment by gajosu** [comment]
I just fixed it, thanks!
